name: convert

on:
  workflow_dispatch:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build book
        run: |-
          npm install -g md-to-pdf
          mkdir -p _output
          echo; echo "Input Folder Listing"
          ls
          echo; echo "Generating PDF"
          for f in README.md; do cat $f; echo; done | md-to-pdf > _output/exported_pdf.pdf
          cd _output
          echo; echo "Output Folder Listing"
          ls
          cd ..
      
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: _output